-- FIPS 10-4 Country Codes Seed Data
-- This file adds FIPS 10-4 codes to region_sources for all countries that have ISO3 codes
-- Generated from Wikipedia FIPS 10-4 list: https://en.wikipedia.org/wiki/List_of_FIPS_country_codes
-- 
-- This SQL uses a CTE to match existing ISO3 codes in region_sources with FIPS codes,
-- then inserts new region_sources entries for FIPS codes where they don't already exist.

WITH fips_mapping AS (
  SELECT * FROM (VALUES
    ('ABW', 'AA'),
    ('AFG', 'AF'),
    ('AGO', 'AO'),
    ('AIA', 'AV'),
    ('ALB', 'AL'),
    ('AND', 'AN'),
    ('ANT', 'NT'),
    ('ARE', 'AE'),
    ('ARG', 'AR'),
    ('ARM', 'AM'),
    ('ASM', 'AQ'),
    ('ATA', 'AY'),
    ('ATF', 'FS'),
    ('ATG', 'AC'),
    ('AUS', 'AT'),
    ('AUT', 'AU'),
    ('AZE', 'AJ'),
    ('BDI', 'BY'),
    ('BEL', 'BE'),
    ('BEN', 'BN'),
    ('BFA', 'UV'),
    ('BGD', 'BG'),
    ('BGR', 'BU'),
    ('BHR', 'BA'),
    ('BHS', 'BF'),
    ('BIH', 'BK'),
    ('BLR', 'BO'),
    ('BLZ', 'BH'),
    ('BMU', 'BD'),
    ('BOL', 'BL'),
    ('BRA', 'BR'),
    ('BRB', 'BB'),
    ('BRN', 'BX'),
    ('BTN', 'BT'),
    ('BWA', 'BC'),
    ('CAF', 'CT'),
    ('CAN', 'CA'),
    ('CCK', 'CK'),
    ('CHE', 'SZ'),
    ('CHL', 'CI'),
    ('CHN', 'CH'),
    ('CIV', 'IV'),
    ('CMR', 'CM'),
    ('COD', 'CG'),
    ('COG', 'CF'),
    ('COK', 'CW'),
    ('COL', 'CO'),
    ('COM', 'CN'),
    ('CPV', 'CV'),
    ('CRI', 'CS'),
    ('CUB', 'CU'),
    ('CXR', 'KT'),
    ('CYM', 'CJ'),
    ('CYP', 'UC'),
    ('CZE', 'EZ'),
    ('DEU', 'GM'),
    ('DJI', 'DJ'),
    ('DMA', 'DO'),
    ('DNK', 'DA'),
    ('DOM', 'DR'),
    ('DZA', 'AG'),
    ('ECU', 'EC'),
    ('EGY', 'EG'),
    ('ERI', 'ER'),
    ('ESH', 'WE'),
    ('ESP', 'SP'),
    ('EST', 'EN'),
    ('ETH', 'ET'),
    ('FIN', 'FI'),
    ('FJI', 'FJ'),
    ('FLK', 'FK'),
    ('FRA', 'FR'),
    ('FRO', 'FO'),
    ('FSM', 'FM'),
    ('GAB', 'GB'),
    ('GBR', 'UK'),
    ('GEO', 'GG'),
    ('GGY', 'GK'),
    ('GHA', 'GH'),
    ('GIB', 'GI'),
    ('GIN', 'GV'),
    ('GLP', 'GP'),
    ('GMB', 'GA'),
    ('GNB', 'PU'),
    ('GNQ', 'EK'),
    ('GRC', 'GR'),
    ('GRD', 'GJ'),
    ('GRL', 'GL'),
    ('GTM', 'GT'),
    ('GUF', 'FG'),
    ('GUM', 'GQ'),
    ('GUY', 'GY'),
    ('HKG', 'HK'),
    ('HMD', 'HM'),
    ('HND', 'HO'),
    ('HRV', 'HR'),
    ('HTI', 'HA'),
    ('HUN', 'HU'),
    ('IDN', 'ID'),
    ('IMN', 'IM'),
    ('IND', 'IN'),
    ('IRL', 'EI'),
    ('IRN', 'IR'),
    ('IRQ', 'IZ'),
    ('ISL', 'IC'),
    ('ISR', 'IS'),
    ('ITA', 'IT'),
    ('JAM', 'JM'),
    ('JEY', 'JE'),
    ('JOR', 'JO'),
    ('JPN', 'JA'),
    ('KAZ', 'KZ'),
    ('KEN', 'KE'),
    ('KGZ', 'KG'),
    ('KHM', 'CB'),
    ('KIR', 'KR'),
    ('KNA', 'SC'),
    ('KOR', 'KS'),
    ('KWT', 'KU'),
    ('LAO', 'LA'),
    ('LBN', 'LE'),
    ('LBR', 'LI'),
    ('LBY', 'LY'),
    ('LCA', 'ST'),
    ('LIE', 'LS'),
    ('LKA', 'CE'),
    ('LSO', 'LT'),
    ('LTU', 'LH'),
    ('LUX', 'LU'),
    ('LVA', 'LG'),
    ('MAC', 'MC'),
    ('MAR', 'MO'),
    ('MCO', 'MN'),
    ('MDA', 'MD'),
    ('MDG', 'MA'),
    ('MDV', 'MV'),
    ('MEX', 'MX'),
    ('MHL', 'RM'),
    ('MKD', 'MK'),
    ('MLI', 'ML'),
    ('MLT', 'MT'),
    ('MMR', 'BM'),
    ('MNE', 'MJ'),
    ('MNG', 'MG'),
    ('MNP', 'CQ'),
    ('MOZ', 'MZ'),
    ('MRT', 'MR'),
    ('MSR', 'MH'),
    ('MTQ', 'MB'),
    ('MUS', 'MP'),
    ('MWI', 'MI'),
    ('MYS', 'MY'),
    ('NAM', 'WA'),
    ('NCL', 'NC'),
    ('NER', 'NG'),
    ('NFK', 'NF'),
    ('NGA', 'NI'),
    ('NIC', 'NU'),
    ('NIU', 'NE'),
    ('NLD', 'NL'),
    ('NOR', 'NO'),
    ('NPL', 'NP'),
    ('NRU', 'NR'),
    ('NZL', 'NZ'),
    ('OMN', 'MU'),
    ('PAK', 'PK'),
    ('PAN', 'PM'),
    ('PCN', 'PC'),
    ('PER', 'PE'),
    ('PHL', 'RP'),
    ('PLW', 'PS'),
    ('PNG', 'PP'),
    ('POL', 'PL'),
    ('PRI', 'RQ'),
    ('PRK', 'KN'),
    ('PRT', 'PO'),
    ('PRY', 'PA'),
    ('PSE', 'GZ'),
    ('PYF', 'FP'),
    ('QAT', 'QA'),
    ('REU', 'RE'),
    ('ROU', 'RO'),
    ('RUS', 'RS'),
    ('RWA', 'RW'),
    ('SAU', 'SA'),
    ('SDN', 'SU'),
    ('SEN', 'SG'),
    ('SGP', 'SN'),
    ('SGS', 'SX'),
    ('SHN', 'SH'),
    ('SJM', 'SV'),
    ('SLB', 'BP'),
    ('SLE', 'SL'),
    ('SLV', 'ES'),
    ('SMR', 'SM'),
    ('SOM', 'SO'),
    ('SPM', 'SB'),
    ('SRB', 'RI'),
    ('SSD', 'OD'),
    ('STP', 'TP'),
    ('SUR', 'NS'),
    ('SVK', 'LO'),
    ('SVN', 'SI'),
    ('SWE', 'SW'),
    ('SWZ', 'WZ'),
    ('SYC', 'SE'),
    ('SYR', 'SY'),
    ('TCA', 'TV'),
    ('TCD', 'CD'),
    ('TGO', 'TO'),
    ('THA', 'TH'),
    ('TJK', 'TI'),
    ('TKL', 'TL'),
    ('TKM', 'TX'),
    ('TLS', 'TT'),
    ('TON', 'TN'),
    ('TTO', 'TD'),
    ('TUN', 'TS'),
    ('TUR', 'TU'),
    ('TWN', 'TW'),
    ('TZA', 'TZ'),
    ('UGA', 'UG'),
    ('UKR', 'UP'),
    ('URY', 'UY'),
    ('USA', 'US'),
    ('UZB', 'UZ'),
    ('VAT', 'VT'),
    ('VCT', 'VC'),
    ('VEN', 'VE'),
    ('VGB', 'VI'),
    ('VIR', 'VQ'),
    ('VNM', 'VM'),
    ('VUT', 'NH'),
    ('WLF', 'WF'),
    ('WSM', 'WS'),
    ('YEM', 'YM'),
    ('ZAF', 'SF'),
    ('ZMB', 'ZA'),
    ('ZWE', 'ZI')
  ) AS t(iso3_code, fips_code)
),
existing_regions AS (
  SELECT DISTINCT r.id as region_id, rs.external_id as iso3_code
  FROM regions r
  INNER JOIN region_sources rs ON r.id = rs.region_id
  WHERE rs.external_id_type = 'iso3166-1-alpha3'
    AND rs.deleted_at IS NULL
    AND r.deleted_at IS NULL
    AND r.level = 'country'
),
regions_to_update AS (
  SELECT 
    er.region_id,
    er.iso3_code,
    fm.fips_code
  FROM existing_regions er
  INNER JOIN fips_mapping fm ON er.iso3_code = fm.iso3_code
  WHERE NOT EXISTS (
    SELECT 1 
    FROM region_sources rs2 
    WHERE rs2.region_id = er.region_id 
      AND rs2.external_id_type = 'fips-10-4'
      AND rs2.external_id = fm.fips_code
      AND rs2.deleted_at IS NULL
  )
)
INSERT INTO region_sources (
  id,
  region_id,
  source,
  external_id_type,
  external_id,
  version,
  is_external,
  created_at
)
SELECT 
  gen_random_uuid(),
  region_id,
  'fips-10-4',
  'fips-10-4',
  fips_code,
  '2024',
  TRUE,
  NOW()
FROM regions_to_update;

-- Verify the insert
SELECT 
  'FIPS codes added' as status,
  COUNT(*) as count
FROM region_sources
WHERE external_id_type = 'fips-10-4'
  AND deleted_at IS NULL;

