// This file will be generated by running: npm run powersync:generate-schema
// The generated schema will be based on powersync/sync-rules.yaml
//
// For now, this is a placeholder. After running the generate script,
// this file will contain the PowerSync schema definitions for the recording app.
//
// To generate the schema:
//   1. Ensure PowerSync CLI is installed: npm install -g @powersync/cli
//   2. Run: npm run powersync:generate-schema
//   3. The generated schema will be written to AppSchema.generated.ts
//
// Note: This placeholder will be replaced by the actual generated schema
// when the PowerSync integration is fully set up.

export {};
